export const STARS = [
  {
    id: "sirius",
    name: "Sirius",
    type: "Etoile",
    constellation: "Canis Major",
    raHours: 6.7525,
    decDeg: -16.7161,
    magnitude: -1.46,
    distance: "8.6 a.l.",
    color: "#dcecff",
    description: "Etoile blanche de type A accompagnee d'une naine blanche, Sirius B.",
    history: "Son lever heliacal servait de repere au calendrier egyptien antique.",
    facts: ["Etoile la plus brillante du ciel nocturne.", "Son nom vient du grec Seirios, le brillant."]
  },
  {
    id: "canopus",
    name: "Canopus",
    type: "Etoile",
    constellation: "Carina",
    raHours: 6.3992,
    decDeg: -52.6957,
    magnitude: -0.74,
    distance: "310 a.l.",
    color: "#fff1d4",
    description: "Supergeante claire tres lumineuse, difficile a voir depuis les hautes latitudes nord.",
    history: "Canopus a longtemps ete utilisee comme etoile de navigation.",
    facts: ["Deuxieme etoile la plus brillante du ciel.", "Visible surtout depuis l'hemisphere sud."]
  },
  {
    id: "arcturus",
    name: "Arcturus",
    type: "Etoile",
    constellation: "Bootes",
    raHours: 14.261,
    decDeg: 19.1825,
    magnitude: -0.05,
    distance: "36.7 a.l.",
    color: "#ffd0a0",
    description: "Geante orange riche en metaux anciens, plus froide que le Soleil.",
    history: "Son nom signifie gardien de l'ourse dans la tradition grecque.",
    facts: ["Tres grand mouvement propre.", "Elle appartient au courant stellaire d'Arcturus."]
  },
  {
    id: "vega",
    name: "Vega",
    type: "Etoile",
    constellation: "Lyra",
    raHours: 18.6156,
    decDeg: 38.7837,
    magnitude: 0.03,
    distance: "25 a.l.",
    color: "#e5efff",
    description: "Etoile blanche rapide entouree d'un disque de poussiere.",
    history: "Vega a longtemps servi de reference pour l'echelle des magnitudes.",
    facts: ["Sommet du Triangle d'ete.", "Elle fut l'etoile polaire il y a environ 12000 ans."]
  },
  {
    id: "capella",
    name: "Capella",
    type: "Etoile",
    constellation: "Auriga",
    raHours: 5.2782,
    decDeg: 45.998,
    magnitude: 0.08,
    distance: "42.9 a.l.",
    color: "#ffe4ae",
    description: "Systeme multiple domine par deux geantes jaunes.",
    history: "Associee a la chevre Amalthee dans plusieurs traditions anciennes.",
    facts: ["Tres brillante en hiver boreal.", "Le systeme contient au moins quatre etoiles."]
  },
  {
    id: "rigel",
    name: "Rigel",
    type: "Etoile",
    constellation: "Orion",
    raHours: 5.2423,
    decDeg: -8.2016,
    magnitude: 0.13,
    distance: "860 a.l.",
    color: "#b8d4ff",
    description: "Supergeante bleue massive, beaucoup plus lumineuse que le Soleil.",
    history: "Marque le pied d'Orion dans les cartes classiques.",
    facts: ["Une des etoiles les plus lumineuses proches a l'oeil nu.", "Sa lumiere bleutee signale une temperature elevee."]
  },
  {
    id: "procyon",
    name: "Procyon",
    type: "Etoile",
    constellation: "Canis Minor",
    raHours: 7.655,
    decDeg: 5.225,
    magnitude: 0.34,
    distance: "11.5 a.l.",
    color: "#f7fbff",
    description: "Etoile blanche-jaune avec une compagne naine blanche.",
    history: "Son nom signifie avant le chien, car elle precede Sirius dans le ciel.",
    facts: ["Tres proche du Soleil.", "Fait partie du Triangle d'hiver."]
  },
  {
    id: "betelgeuse",
    name: "Betelgeuse",
    type: "Etoile",
    constellation: "Orion",
    raHours: 5.9195,
    decDeg: 7.4071,
    magnitude: 0.5,
    distance: "550 a.l.",
    color: "#ff9a6f",
    description: "Supergeante rouge variable, proche de la fin de sa vie stellaire.",
    history: "Son nom vient de l'arabe et designe l'epaule d'Orion.",
    facts: ["Son eclat varie nettement.", "Elle deviendra une supernova a l'echelle astronomique."]
  },
  {
    id: "achernar",
    name: "Achernar",
    type: "Etoile",
    constellation: "Eridanus",
    raHours: 1.6286,
    decDeg: -57.2368,
    magnitude: 0.46,
    distance: "139 a.l.",
    color: "#c8ddff",
    description: "Etoile bleue tres aplatie par sa rotation rapide.",
    history: "Son nom signifie fin de la riviere celeste Eridan.",
    facts: ["Rotation proche de la limite de rupture.", "Visible surtout depuis le sud."]
  },
  {
    id: "altair",
    name: "Altair",
    type: "Etoile",
    constellation: "Aquila",
    raHours: 19.8464,
    decDeg: 8.8683,
    magnitude: 0.77,
    distance: "16.7 a.l.",
    color: "#eef5ff",
    description: "Etoile blanche proche, aplatie par une rotation tres rapide.",
    history: "Pilier des mythes du Triangle d'ete en Asie orientale.",
    facts: ["Tourne en moins de dix heures.", "Sommet du Triangle d'ete avec Vega et Deneb."]
  },
  {
    id: "acrux",
    name: "Acrux",
    type: "Etoile",
    constellation: "Crux",
    raHours: 12.4433,
    decDeg: -63.0991,
    magnitude: 0.76,
    distance: "320 a.l.",
    color: "#bfd8ff",
    description: "Systeme multiple bleu formant la base de la Croix du Sud.",
    history: "La Croix du Sud est un repere majeur de navigation australe.",
    facts: ["Visible depuis les tropiques et l'hemisphere sud.", "Plusieurs composants massifs forment le systeme."]
  },
  {
    id: "aldebaran",
    name: "Aldebaran",
    type: "Etoile",
    constellation: "Taurus",
    raHours: 4.5987,
    decDeg: 16.5093,
    magnitude: 0.87,
    distance: "65 a.l.",
    color: "#ffbf7d",
    description: "Geante orange situee visuellement devant l'amas des Hyades.",
    history: "Son nom signifie le suiveur, car elle suit les Pleiades.",
    facts: ["Oeil du Taureau.", "Elle n'appartient pas physiquement aux Hyades."]
  },
  {
    id: "spica",
    name: "Spica",
    type: "Etoile",
    constellation: "Virgo",
    raHours: 13.4199,
    decDeg: -11.1613,
    magnitude: 0.98,
    distance: "250 a.l.",
    color: "#b9d4ff",
    description: "Binaire massive bleue dont les etoiles se deformeraient par marees.",
    history: "Associee a l'epi de ble tenu par la Vierge.",
    facts: ["Etoile double spectroscopique.", "Tres utile pour reperer la constellation de la Vierge."]
  },
  {
    id: "antares",
    name: "Antares",
    type: "Etoile",
    constellation: "Scorpius",
    raHours: 16.4901,
    decDeg: -26.432,
    magnitude: 1.06,
    distance: "550 a.l.",
    color: "#ff7f5f",
    description: "Supergeante rouge dont la couleur rivalise avec celle de Mars.",
    history: "Son nom signifie rival d'Ares, donc rival de Mars.",
    facts: ["Coeur du Scorpion.", "Son diametre depasserait largement l'orbite de Mars si elle remplacait le Soleil."]
  },
  {
    id: "pollux",
    name: "Pollux",
    type: "Etoile",
    constellation: "Gemini",
    raHours: 7.7553,
    decDeg: 28.0262,
    magnitude: 1.14,
    distance: "34 a.l.",
    color: "#ffd9a2",
    description: "Geante orange autour de laquelle une exoplanete a ete detectee.",
    history: "Un des deux jumeaux celestes avec Castor.",
    facts: ["Etoile brillante la plus proche avec une planete connue.", "Plus froide et plus grande que le Soleil."]
  },
  {
    id: "fomalhaut",
    name: "Fomalhaut",
    type: "Etoile",
    constellation: "Piscis Austrinus",
    raHours: 22.9608,
    decDeg: -29.6222,
    magnitude: 1.16,
    distance: "25 a.l.",
    color: "#eaf2ff",
    description: "Etoile blanche entouree d'un anneau de debris observe en image directe.",
    history: "Son nom signifie bouche du poisson austral.",
    facts: ["Souvent appelee l'etoile solitaire de l'automne.", "Son disque de poussiere est tres etudie."]
  },
  {
    id: "deneb",
    name: "Deneb",
    type: "Etoile",
    constellation: "Cygnus",
    raHours: 20.6905,
    decDeg: 45.2803,
    magnitude: 1.25,
    distance: "2600 a.l.",
    color: "#d7e7ff",
    description: "Supergeante blanche immense et tres lointaine.",
    history: "Son nom designe la queue du Cygne.",
    facts: ["Sommet du Triangle d'ete.", "Elle parait brillante malgre son enorme distance."]
  },
  {
    id: "regulus",
    name: "Regulus",
    type: "Etoile",
    constellation: "Leo",
    raHours: 10.1395,
    decDeg: 11.9672,
    magnitude: 1.35,
    distance: "79 a.l.",
    color: "#d7e8ff",
    description: "Etoile bleue-blanche rapide situee pres de l'ecliptique.",
    history: "Son nom latin signifie petit roi.",
    facts: ["Coeur du Lion.", "La Lune et les planetes peuvent passer tres pres d'elle."]
  },
  {
    id: "polaris",
    name: "Polaris",
    type: "Etoile",
    constellation: "Ursa Minor",
    raHours: 2.5303,
    decDeg: 89.2641,
    magnitude: 1.98,
    distance: "447 a.l.",
    color: "#f4f2ff",
    description: "Cepheide jaune proche du pole nord celeste.",
    history: "Etoile polaire moderne pour la navigation dans l'hemisphere nord.",
    facts: ["Son altitude indique presque la latitude nord.", "Elle n'est pas exactement au pole celeste."]
  },
  {
    id: "bellatrix",
    name: "Bellatrix",
    type: "Etoile",
    constellation: "Orion",
    raHours: 5.4189,
    decDeg: 6.3497,
    magnitude: 1.64,
    distance: "250 a.l.",
    color: "#c6dcff",
    description: "Geante bleue formant l'epaule ouest d'Orion.",
    history: "Son nom latin signifie guerriere.",
    facts: ["Repere net dans Orion.", "Beaucoup plus chaude que le Soleil."]
  },
  {
    id: "saiph",
    name: "Saiph",
    type: "Etoile",
    constellation: "Orion",
    raHours: 5.7959,
    decDeg: -9.6696,
    magnitude: 2.07,
    distance: "650 a.l.",
    color: "#b9d6ff",
    description: "Supergeante bleue marquant le genou d'Orion.",
    history: "Son nom vient d'une expression arabe liee a l'epee.",
    facts: ["Tres lumineuse mais plus faible visuellement que Rigel.", "Appartient a la silhouette principale d'Orion."]
  },
  {
    id: "alnitak",
    name: "Alnitak",
    type: "Etoile",
    constellation: "Orion",
    raHours: 5.6793,
    decDeg: -1.9426,
    magnitude: 1.74,
    distance: "1260 a.l.",
    color: "#bfd9ff",
    description: "Systeme multiple bleu a l'est de la ceinture d'Orion.",
    history: "Son nom designe la ceinture.",
    facts: ["Voisine apparente de la Nebuleuse de la Flamme.", "Membre de l'association Orion OB1."]
  },
  {
    id: "alnilam",
    name: "Alnilam",
    type: "Etoile",
    constellation: "Orion",
    raHours: 5.6036,
    decDeg: -1.2019,
    magnitude: 1.69,
    distance: "2000 a.l.",
    color: "#c7ddff",
    description: "Supergeante bleue au centre de la ceinture d'Orion.",
    history: "Nommee d'apres un rang de perles.",
    facts: ["Parmi les etoiles les plus lumineuses connues visibles a l'oeil nu.", "Son vent stellaire est puissant."]
  },
  {
    id: "mintaka",
    name: "Mintaka",
    type: "Etoile",
    constellation: "Orion",
    raHours: 5.5334,
    decDeg: -0.2991,
    magnitude: 2.23,
    distance: "1200 a.l.",
    color: "#c9ddff",
    description: "Systeme multiple a l'ouest de la ceinture d'Orion.",
    history: "Son nom signifie aussi ceinture en arabe.",
    facts: ["Situee presque sur l'equateur celeste.", "La ceinture d'Orion se leve presque plein est."]
  },
  {
    id: "dubhe",
    name: "Dubhe",
    type: "Etoile",
    constellation: "Ursa Major",
    raHours: 11.0621,
    decDeg: 61.751,
    magnitude: 1.79,
    distance: "123 a.l.",
    color: "#ffe1ad",
    description: "Geante orange formant le bord de la Grande Casserole.",
    history: "Avec Merak, elle pointe vers Polaris.",
    facts: ["Une des deux etoiles repere du pole nord.", "N'appartient pas au groupe mobile principal de la Grande Ourse."]
  },
  {
    id: "merak",
    name: "Merak",
    type: "Etoile",
    constellation: "Ursa Major",
    raHours: 11.0307,
    decDeg: 56.3824,
    magnitude: 2.37,
    distance: "79 a.l.",
    color: "#e9f1ff",
    description: "Etoile blanche de la Grande Casserole.",
    history: "Ligne Merak-Dubhe prolongee mene a Polaris.",
    facts: ["Membre du groupe mobile de la Grande Ourse.", "Tres utile pour l'orientation nocturne."]
  },
  {
    id: "phecda",
    name: "Phecda",
    type: "Etoile",
    constellation: "Ursa Major",
    raHours: 11.8972,
    decDeg: 53.6948,
    magnitude: 2.44,
    distance: "83 a.l.",
    color: "#edf4ff",
    description: "Etoile blanche formant un coin du bol de la Grande Casserole.",
    history: "Son nom est lie a la cuisse de l'ourse.",
    facts: ["Membre du groupe mobile de la Grande Ourse.", "Reliee a Megrez et Merak dans l'asterisme."]
  },
  {
    id: "megrez",
    name: "Megrez",
    type: "Etoile",
    constellation: "Ursa Major",
    raHours: 12.2571,
    decDeg: 57.0326,
    magnitude: 3.31,
    distance: "81 a.l.",
    color: "#f1f6ff",
    description: "Etoile la plus discrete de l'asterisme de la Grande Casserole.",
    history: "Elle relie le bol au manche.",
    facts: ["Sa faible luminosite aide a juger la transparence du ciel.", "Membre du groupe mobile de la Grande Ourse."]
  },
  {
    id: "alioth",
    name: "Alioth",
    type: "Etoile",
    constellation: "Ursa Major",
    raHours: 12.9005,
    decDeg: 55.9598,
    magnitude: 1.76,
    distance: "82 a.l.",
    color: "#edf5ff",
    description: "Etoile blanche chimiquement particuliere du manche de la Grande Casserole.",
    history: "Nom classique de la queue de l'ourse.",
    facts: ["La plus brillante de la Grande Ourse.", "Sa surface presente des zones chimiques variables."]
  },
  {
    id: "mizar",
    name: "Mizar",
    type: "Etoile",
    constellation: "Ursa Major",
    raHours: 13.3988,
    decDeg: 54.9254,
    magnitude: 2.23,
    distance: "83 a.l.",
    color: "#e8f1ff",
    description: "Systeme multiple visible pres d'Alcor.",
    history: "Mizar et Alcor etaient un test classique d'acuite visuelle.",
    facts: ["Une des premieres binaires telescopiques observees.", "Partie du manche de la Grande Casserole."]
  },
  {
    id: "alkaid",
    name: "Alkaid",
    type: "Etoile",
    constellation: "Ursa Major",
    raHours: 13.7923,
    decDeg: 49.3133,
    magnitude: 1.85,
    distance: "104 a.l.",
    color: "#cfe2ff",
    description: "Etoile bleue-blanche au bout du manche de la Grande Casserole.",
    history: "Son nom evoque le chef des pleureuses dans une tradition arabe.",
    facts: ["Elle ne partage pas le mouvement du groupe mobile principal.", "Repere facile du printemps boreal."]
  },
  {
    id: "schedar",
    name: "Schedar",
    type: "Etoile",
    constellation: "Cassiopeia",
    raHours: 0.6751,
    decDeg: 56.5373,
    magnitude: 2.24,
    distance: "230 a.l.",
    color: "#ffd0a0",
    description: "Geante orange de la forme en W de Cassiopee.",
    history: "Son nom vient de l'arabe pour poitrine.",
    facts: ["Circumpolaire dans une grande partie de l'Europe.", "Bonne cible pour apprendre la carte du nord."]
  },
  {
    id: "caph",
    name: "Caph",
    type: "Etoile",
    constellation: "Cassiopeia",
    raHours: 0.1529,
    decDeg: 59.1498,
    magnitude: 2.28,
    distance: "55 a.l.",
    color: "#f5fbff",
    description: "Etoile blanche-jaune variable de Cassiopee.",
    history: "Une extremite du W de Cassiopee.",
    facts: ["Tourne rapidement.", "Presente de petites pulsations."]
  },
  {
    id: "navi",
    name: "Navi",
    type: "Etoile",
    constellation: "Cassiopeia",
    raHours: 0.9451,
    decDeg: 60.7167,
    magnitude: 2.47,
    distance: "550 a.l.",
    color: "#c5dcff",
    description: "Etoile bleue variable aussi connue sous Gamma Cassiopeiae.",
    history: "Surnom moderne donne en hommage a l'astronaute Virgil Ivan Grissom.",
    facts: ["Prototype d'une classe d'etoiles Be variables.", "Entouree de gaz equatorial."]
  },
  {
    id: "ruchbah",
    name: "Ruchbah",
    type: "Etoile",
    constellation: "Cassiopeia",
    raHours: 1.4303,
    decDeg: 60.2353,
    magnitude: 2.68,
    distance: "99 a.l.",
    color: "#e9f2ff",
    description: "Binaire eclipsante dans Cassiopee.",
    history: "Son nom signifie genou.",
    facts: ["Partie centrale du W.", "Sa luminosite varie legerement."]
  },
  {
    id: "segin",
    name: "Segin",
    type: "Etoile",
    constellation: "Cassiopeia",
    raHours: 1.9066,
    decDeg: 63.67,
    magnitude: 3.35,
    distance: "410 a.l.",
    color: "#bcd7ff",
    description: "Etoile bleue formant une pointe de Cassiopee.",
    history: "Une extremite de la figure en W.",
    facts: ["Jeune et chaude.", "Visible sous un bon ciel malgre son eclat modeste."]
  },
  {
    id: "sadr",
    name: "Sadr",
    type: "Etoile",
    constellation: "Cygnus",
    raHours: 20.3705,
    decDeg: 40.2567,
    magnitude: 2.23,
    distance: "1800 a.l.",
    color: "#fff2c8",
    description: "Supergeante jaune au centre de la Croix du Nord.",
    history: "Son nom signifie poitrine.",
    facts: ["Situee dans une zone riche de nebuleuses.", "Relie les ailes et le cou du Cygne."]
  },
  {
    id: "gienah",
    name: "Gienah",
    type: "Etoile",
    constellation: "Cygnus",
    raHours: 20.7702,
    decDeg: 33.9703,
    magnitude: 2.48,
    distance: "73 a.l.",
    color: "#ffd0a6",
    description: "Geante orange marquant une aile du Cygne.",
    history: "Son nom evoque l'aile.",
    facts: ["Assez proche du Soleil.", "Contraste avec les etoiles bleues voisines."]
  },
  {
    id: "albireo",
    name: "Albireo",
    type: "Etoile",
    constellation: "Cygnus",
    raHours: 19.512,
    decDeg: 27.9597,
    magnitude: 3.05,
    distance: "430 a.l.",
    color: "#ffd6a2",
    description: "Double celebre aux couleurs orange et bleue.",
    history: "Cible classique des petits telescopes.",
    facts: ["Marque le bec du Cygne.", "Son contraste de couleur est spectaculaire."]
  },
  {
    id: "delta-cygni",
    name: "Delta Cygni",
    type: "Etoile",
    constellation: "Cygnus",
    raHours: 19.7496,
    decDeg: 45.1308,
    magnitude: 2.86,
    distance: "165 a.l.",
    color: "#d9e9ff",
    description: "Systeme multiple formant l'autre aile du Cygne.",
    history: "Une branche de la Croix du Nord.",
    facts: ["Elle sera proche du pole nord celeste dans plusieurs millenaires.", "Binaire serree pour les observateurs."]
  },
  {
    id: "sheliak",
    name: "Sheliak",
    type: "Etoile",
    constellation: "Lyra",
    raHours: 18.8347,
    decDeg: 33.3627,
    magnitude: 3.52,
    distance: "960 a.l.",
    color: "#cfe3ff",
    description: "Systeme binaire eclipsant variable.",
    history: "Son nom vient d'une appellation arabe de la lyre.",
    facts: ["Sa luminosite change avec ses eclipses.", "Avec Sulafat, elle encadre la nebuleuse de l'Anneau."]
  },
  {
    id: "sulafat",
    name: "Sulafat",
    type: "Etoile",
    constellation: "Lyra",
    raHours: 18.9824,
    decDeg: 32.6896,
    magnitude: 3.25,
    distance: "620 a.l.",
    color: "#c8ddff",
    description: "Geante bleue de la petite Lyre.",
    history: "Son nom evoque la tortue, liee a l'origine mythique de la lyre.",
    facts: ["Pres de la nebuleuse de l'Anneau.", "Complete la petite figure autour de Vega."]
  },
  {
    id: "shaula",
    name: "Shaula",
    type: "Etoile",
    constellation: "Scorpius",
    raHours: 17.5601,
    decDeg: -37.1038,
    magnitude: 1.62,
    distance: "570 a.l.",
    color: "#bed8ff",
    description: "Systeme multiple bleu a l'aiguillon du Scorpion.",
    history: "Son nom signifie aiguillon.",
    facts: ["Tres lumineuse.", "Associee visuellement a Lesath dans la queue du Scorpion."]
  },
  {
    id: "sargas",
    name: "Sargas",
    type: "Etoile",
    constellation: "Scorpius",
    raHours: 17.6219,
    decDeg: -42.9978,
    magnitude: 1.86,
    distance: "270 a.l.",
    color: "#fff0ca",
    description: "Geante jaune-blanche tres brillante de la queue du Scorpion.",
    history: "Son nom classique est ancien mais d'origine incertaine.",
    facts: ["Visible bas sur l'horizon depuis l'Europe.", "Beaucoup plus lumineuse que le Soleil."]
  },
  {
    id: "dschubba",
    name: "Dschubba",
    type: "Etoile",
    constellation: "Scorpius",
    raHours: 16.0056,
    decDeg: -22.6217,
    magnitude: 2.29,
    distance: "400 a.l.",
    color: "#c6dcff",
    description: "Etoile bleue de la tete du Scorpion.",
    history: "Son nom vient de l'arabe pour front.",
    facts: ["Etoile variable de type Be.", "Son eclat a deja montre des episodes de hausse."]
  },
  {
    id: "elnath",
    name: "Elnath",
    type: "Etoile",
    constellation: "Taurus",
    raHours: 5.4382,
    decDeg: 28.6075,
    magnitude: 1.65,
    distance: "134 a.l.",
    color: "#d5e6ff",
    description: "Geante bleue-blanche formant une corne du Taureau.",
    history: "Anciennement partagee avec Auriga dans certaines cartes.",
    facts: ["Situee pres du plan de la Voie lactee.", "Repere de l'hiver boreal."]
  },
  {
    id: "alcyone",
    name: "Alcyone",
    type: "Etoile",
    constellation: "Taurus",
    raHours: 3.7914,
    decDeg: 24.1051,
    magnitude: 2.87,
    distance: "440 a.l.",
    color: "#c9ddff",
    description: "Etoile la plus brillante des Pleiades.",
    history: "Les Pleiades sont mentionnees dans de nombreuses cultures anciennes.",
    facts: ["Jeune etoile bleue.", "Entouree par l'amas ouvert M45."]
  },
  {
    id: "denebola",
    name: "Denebola",
    type: "Etoile",
    constellation: "Leo",
    raHours: 11.8177,
    decDeg: 14.5721,
    magnitude: 2.14,
    distance: "36 a.l.",
    color: "#eef5ff",
    description: "Etoile blanche formant la queue du Lion.",
    history: "Son nom signifie queue du lion.",
    facts: ["Tres proche a l'echelle stellaire.", "Possede un disque de debris."]
  },
  {
    id: "algieba",
    name: "Algieba",
    type: "Etoile",
    constellation: "Leo",
    raHours: 10.3329,
    decDeg: 19.8415,
    magnitude: 2.08,
    distance: "130 a.l.",
    color: "#ffd6a5",
    description: "Double de geantes dorees dans la criniere du Lion.",
    history: "Nommee d'apres le front du Lion.",
    facts: ["Belle double au telescope.", "Une planete geante a ete detectee autour d'un composant."]
  },
  {
    id: "zosma",
    name: "Zosma",
    type: "Etoile",
    constellation: "Leo",
    raHours: 11.2351,
    decDeg: 20.5237,
    magnitude: 2.56,
    distance: "58 a.l.",
    color: "#f0f5ff",
    description: "Etoile blanche situee sur le dos du Lion.",
    history: "Son nom vient d'un mot grec associe a la ceinture.",
    facts: ["Rotation rapide.", "Complete la silhouette du Lion."]
  }
];

export const SOLAR_SYSTEM_OBJECTS = {
  sun: {
    id: "sun",
    name: "Soleil",
    type: "Etoile",
    constellation: "Ecliptique",
    magnitude: -26.7,
    distance: "1 UA",
    color: "#ffd36c",
    description: "Etoile de type G composee surtout d'hydrogene et d'helium.",
    history: "Centre du systeme solaire et source principale d'energie de la Terre.",
    facts: ["Sa lumiere met environ 8 minutes a nous atteindre.", "Ne jamais viser le Soleil directement."]
  },
  moon: {
    id: "moon",
    name: "Lune",
    type: "Satellite naturel",
    constellation: "Ecliptique",
    magnitude: -12.7,
    distance: "384000 km en moyenne",
    color: "#f3f0e8",
    description: "Satellite rocheux de la Terre, visible par la lumiere solaire reflechie.",
    history: "Premier astre visite par des humains pendant Apollo 11 en 1969.",
    facts: ["Elle s'eloigne de la Terre d'environ 3.8 cm par an.", "Ses phases dependent de son angle avec le Soleil."]
  },
  mercury: {
    id: "mercury",
    name: "Mercure",
    type: "Planete",
    constellation: "Ecliptique",
    magnitude: -0.2,
    distance: "0.6 a 1.4 UA",
    color: "#d8d1c5",
    description: "Petite planete rocheuse proche du Soleil, visible bas au crepuscule.",
    history: "Connue depuis l'Antiquite pour son mouvement rapide.",
    facts: ["Annee de 88 jours terrestres.", "Atmosphere presque inexistante."]
  },
  venus: {
    id: "venus",
    name: "Venus",
    type: "Planete",
    constellation: "Ecliptique",
    magnitude: -4.4,
    distance: "0.3 a 1.7 UA",
    color: "#ffe0a8",
    description: "Planete rocheuse couverte de nuages denses et tres reflechissants.",
    history: "Souvent appelee etoile du matin ou du soir.",
    facts: ["Planete la plus brillante vue depuis la Terre.", "Son atmosphere est dominee par le dioxyde de carbone."]
  },
  mars: {
    id: "mars",
    name: "Mars",
    type: "Planete",
    constellation: "Ecliptique",
    magnitude: -1.5,
    distance: "0.5 a 2.7 UA",
    color: "#ff8b64",
    description: "Planete rocheuse rougeatre, coloree par des oxydes de fer.",
    history: "Associee a la guerre dans de nombreuses mythologies.",
    facts: ["Possede Olympus Mons, volcan geant.", "Deux petits satellites: Phobos et Deimos."]
  },
  jupiter: {
    id: "jupiter",
    name: "Jupiter",
    type: "Planete",
    constellation: "Ecliptique",
    magnitude: -2.6,
    distance: "4.2 a 6.2 UA",
    color: "#f3d6aa",
    description: "Geante gazeuse composee surtout d'hydrogene et d'helium.",
    history: "Ses quatre grandes lunes furent observees par Galilee en 1610.",
    facts: ["Plus grande planete du systeme solaire.", "Sa Grande Tache Rouge est une tempete persistante."]
  },
  saturn: {
    id: "saturn",
    name: "Saturne",
    type: "Planete",
    constellation: "Ecliptique",
    magnitude: 0.5,
    distance: "8 a 11 UA",
    color: "#f6e2ad",
    description: "Geante gazeuse celebre pour son systeme d'anneaux de glace et de poussiere.",
    history: "Connue depuis l'Antiquite; ses anneaux furent compris au XVIIe siecle.",
    facts: ["Moins dense que l'eau en moyenne.", "Titan est une de ses grandes lunes."]
  }
};

export const CONSTELLATIONS = [
  {
    id: "orion",
    name: "Orion",
    type: "Constellation",
    constellation: "Orion",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["betelgeuse", "bellatrix", "mintaka", "alnilam", "alnitak", "saiph", "rigel"],
    lines: [
      ["betelgeuse", "bellatrix"],
      ["betelgeuse", "alnitak"],
      ["bellatrix", "mintaka"],
      ["mintaka", "alnilam"],
      ["alnilam", "alnitak"],
      ["alnitak", "saiph"],
      ["mintaka", "rigel"],
      ["saiph", "rigel"]
    ],
    description: "Grande constellation d'hiver, reconnaissable a sa ceinture de trois etoiles.",
    history: "Orion represente un chasseur dans la mythologie grecque.",
    facts: ["La nebuleuse d'Orion se situe sous la ceinture.", "Visible depuis presque toute la Terre."]
  },
  {
    id: "ursa-major",
    name: "Ursa Major",
    type: "Constellation",
    constellation: "Ursa Major",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["dubhe", "merak", "phecda", "megrez", "alioth", "mizar", "alkaid"],
    lines: [
      ["dubhe", "merak"],
      ["merak", "phecda"],
      ["phecda", "megrez"],
      ["megrez", "dubhe"],
      ["megrez", "alioth"],
      ["alioth", "mizar"],
      ["mizar", "alkaid"]
    ],
    description: "Constellation boreale connue pour l'asterisme de la Grande Casserole.",
    history: "Elle sert de repere pour retrouver Polaris et le nord celeste.",
    facts: ["Circumpolaire dans une grande partie de l'Europe.", "Mizar et Alcor forment un couple visuel fameux."]
  },
  {
    id: "cassiopeia",
    name: "Cassiopeia",
    type: "Constellation",
    constellation: "Cassiopeia",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["caph", "schedar", "navi", "ruchbah", "segin"],
    lines: [
      ["caph", "schedar"],
      ["schedar", "navi"],
      ["navi", "ruchbah"],
      ["ruchbah", "segin"]
    ],
    description: "Constellation en W, brillante dans le ciel du nord.",
    history: "Dans la mythologie grecque, Cassiopee est la reine d'Ethiopie.",
    facts: ["Facile a reperer face a la Grande Ourse autour du pole.", "Traverse une zone riche de la Voie lactee."]
  },
  {
    id: "cygnus",
    name: "Cygnus",
    type: "Constellation",
    constellation: "Cygnus",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["deneb", "sadr", "gienah", "delta-cygni", "albireo"],
    lines: [
      ["deneb", "sadr"],
      ["sadr", "albireo"],
      ["sadr", "gienah"],
      ["sadr", "delta-cygni"]
    ],
    description: "Le Cygne dessine la Croix du Nord au coeur de la Voie lactee.",
    history: "Associe a plusieurs metamorphoses de Zeus dans la tradition grecque.",
    facts: ["Deneb est un sommet du Triangle d'ete.", "Albireo est une double coloree celebre."]
  },
  {
    id: "lyra",
    name: "Lyra",
    type: "Constellation",
    constellation: "Lyra",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["vega", "sheliak", "sulafat"],
    lines: [
      ["vega", "sheliak"],
      ["vega", "sulafat"],
      ["sheliak", "sulafat"]
    ],
    description: "Petite constellation dominee par Vega.",
    history: "Elle represente la lyre d'Orphee.",
    facts: ["Contient la nebuleuse de l'Anneau M57.", "Tres visible les soirs d'ete boreal."]
  },
  {
    id: "scorpius",
    name: "Scorpius",
    type: "Constellation",
    constellation: "Scorpius",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["dschubba", "antares", "shaula", "sargas"],
    lines: [
      ["dschubba", "antares"],
      ["antares", "shaula"],
      ["shaula", "sargas"]
    ],
    description: "Constellation australe spectaculaire avec Antares comme coeur rouge.",
    history: "Le Scorpion est l'adversaire mythologique d'Orion.",
    facts: ["Tres riche en amas stellaires.", "Elle reste basse depuis l'Europe du nord."]
  },
  {
    id: "taurus",
    name: "Taurus",
    type: "Constellation",
    constellation: "Taurus",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["aldebaran", "elnath", "alcyone"],
    lines: [
      ["aldebaran", "elnath"],
      ["aldebaran", "alcyone"]
    ],
    description: "Constellation du Taureau, marquee par Aldebaran, les Hyades et les Pleiades.",
    history: "Une des constellations zodiacales les plus anciennes.",
    facts: ["Les Pleiades forment l'amas M45.", "Aldebaran est visuellement devant les Hyades."]
  },
  {
    id: "leo",
    name: "Leo",
    type: "Constellation",
    constellation: "Leo",
    magnitude: "--",
    distance: "Plusieurs distances",
    stars: ["regulus", "algieba", "zosma", "denebola"],
    lines: [
      ["regulus", "algieba"],
      ["algieba", "zosma"],
      ["zosma", "denebola"]
    ],
    description: "Constellation zodiacale du Lion, bien visible au printemps boreal.",
    history: "Associee au lion de Nemee dans la mythologie grecque.",
    facts: ["Regulus est proche de l'ecliptique.", "Le Lion sert de porte d'entree vers plusieurs galaxies."]
  }
];
